version: "3.8"

# uffizzi integration
x-uffizzi:
  ingress:
    service: nginx
    port: 8081
services:

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx-uffizzi:/etc/nginx


  postgres:
   image: postgres
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=iris
     - PGDATA=/tmp
   volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./uffizzi-db-script/:/docker-entrypoint-initdb.d/
   deploy:
          resources:
            limits:
              memory: 500M

  mindsdb:
    image: mindsdb/mindsdb
    volumes:
      - mindsdb-data:/data
    # #  - ./mindsdb/integrations:/app/integrations
    #  - ./mindsdb/interfaces:/app/interfaces
    #  - ./mindsdb/migrations:/app/migrations
    #  - ./mindsdb/utilities:/app/utilities
    #  - ./mindsdb/__about__.py:/app/__about__.py
    #  - ./mindsdb/__init__.py:/app/__init__.py
    #  - ./mindsdb/__main__.py:/app/__main.py__
    #  - /app/__pycache__/
    #  - /app/api/__pycache__/

    #  - /app/interfaces/__pycache__/
    #  - /app/migrations/__pycache__/
    #  - /app/utilities/__pycache__/
    ports:
      - "47334:47334"
      - "47335:47335"
    # command: bash -c "cd /mindsdb && python -m mindsdb"
    environment:
      MINDSDB_DOCKER_ENV: "True"
      MINDSDB_STORAGE_DIR: "/mindsdb/var"
      FLASK_DEBUG: "1"
      FLASK_ENV: "production"
      FLASK_APP: "/mindsdb/mindsdb/__main__.py"
      MDB_CONFIG_CONTENT: '{"api": {"postgres": {"host": "localhost", "password": "postgres", "port": "5432", "user": "postgres", "database": "postgres"}}}'
    # healthcheck:
    #   test:  ["CMD", "curl", "-f", "http://localhost:47334/api/util/ping"]
    #   interval: 30s
    #   timeout: 4s
    #   retries: 100
    deploy:
            resources:
              limits:
                memory: 4000M


volumes:
  postgres_data:
  mindsdb-data:

