version: "3.8"

# uffizzi integration
x-uffizzi:
  ingress:
    service: nginx
    port: 8081
services:

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx-uffizzi:/etc/nginx


  postgres:
   image: postgres
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=iris
     - PGDATA=/tmp
   volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./uffizzi-db-script/:/docker-entrypoint-initdb.d/
   deploy:
          resources:
            limits:
              memory: 500M

  mindsdb:
    image: "${MINDSDB_IMAGE}"
    ports:
      - "47334:47334"
    environment:
      MINDSDB_DOCKER_ENV: "True"
      MINDSDB_STORAGE_DIR: "/mindsdb/var"
      FLASK_DEBUG: "1"
      FLASK_ENV: "develop"
      FLASK_APP: "mindsdb/mindsdb/__main__.py"

    entrypoint: /bin/bash
    command:
         - "-c"
         - "apt update &&
            apt install unzip -y &&
            URL='https://github.com/${{ github.actor }}/${{ github.event.repository.name }}/archive/refs/heads/uffizzi.zip' &&
            echo URL $URL
            wget '$URL' &&
            unzip uffizzi.zip && wait &&
            rm -rf mindsdb &&
            mv mindsdb-uffizzi mindsdb &&
            chmod +x mindsdb/ &&
            cd mindsdb &&
            python -m mindsdb
            "
    deploy:
            resources:
              limits:
                memory: 2000M


  hugginggace_ml_handler:
    image: "${ML_HANDLER_IMAGE}"
    environment:
      # have to share mindsdb database, because it doens't work without it
      MINDSDB_STORAGE_DIR: "/mindsdb/var"
    entrypoint: /bin/sh
    command:
          - "-c"
          - "apt update &&
            apt install unzip -y &&
            wget https://github.com/ShrutiC-git/mindsdb/archive/refs/heads/uffizzi.zip &&
            unzip uffizzi.zip && wait &&
            rm -rf mindsdb &&
            mv mindsdb-uffizzi mindsdb &&
            chmod +x mindsdb/ &&
            chmod +x mindsdb/mindsdb/ &&
            python /mindsdb/mindsdb/integrations/handlers_wrapper/ml_handler_service.py"
    deploy:
            resources:
              limits:
                memory: 500M


  db_handler:
    image: "${DB_HANDLER_IMAGE}"
    entrypoint: /bin/sh
    command:
          - "-c"
          - "apt update &&
            apt install unzip -y &&
            wget https://github.com/ShrutiC-git/mindsdb/archive/refs/heads/uffizzi.zip &&
            unzip uffizzi.zip && wait &&
            rm -rf mindsdb &&
            mv mindsdb-uffizzi mindsdb &&
            chmod +x mindsdb/ &&
            chmod +x mindsdb/mindsdb &&
            python mindsdb/mindsdb/integrations/handlers_wrapper/db_handler_service.py"
    deploy:
            resources:
              limits:
                memory: 500M
    environment:
      - 'PARAMS={"connection_data": {"host": "localhost", "port": "5432", "user": "postgres", "password": "postgres", "database": "iris", "ssl": false}, "name": "postgres", "type": "postgres"}'

volumes:
  postgres_data:

